// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package mzxml


case class NamevalueType(value: scalaxb.DataRecord[Any],
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map.empty) {
  lazy val name = attributes.get("@name") map { _.as[String]}
  lazy val valueAttribute = attributes.get("@value") map { _.as[scalaxb.DataRecord[Any]]}
  lazy val typeValue = attributes.get("@type") map { _.as[scalaxb.DataRecord[Any]]}
}

      
      


trait OntologyEntryTypable {
  def category: String
  def valueAttribute: String
}


case class OntologyEntryType(attributes: Map[String, scalaxb.DataRecord[Any]] = Map.empty) extends OntologyEntryTypable {
  lazy val category = attributes("@category").as[String]
  lazy val valueAttribute = attributes("@value").as[String]
}

      
      

