addSbtPlugin("com.eed3si9n"  % "sbt-assembly"         % "1.2.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage"        % "2.0.0")
//addSbtPlugin("io.crashbox"        % "sbt-gpg"                       % "0.2.1")
//addSbtPlugin("com.github.sbt"     % "sbt-release"                   % "1.1.0")
//addSbtPlugin("com.github.sbt"     % "sbt-github-actions"            % "0.19.0")
addSbtPlugin("io.shiftleft"  % "sbt-ci-release-early" % "2.0.45")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.12")